// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: support_auth.proto

package support_auth_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Перечисление возможных ролей
type Role int32

const (
	Role_ROLE_UNSPECIFIED Role = 0 // Значение по умолчанию (ошибка)
	Role_ROLE_CLIENT      Role = 1 // Обычный авторизованный покупатель
	Role_ROLE_OPERATOR    Role = 2 // Сотрудник поддержки (менеджер)
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "ROLE_CLIENT",
		2: "ROLE_OPERATOR",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"ROLE_CLIENT":      1,
		"ROLE_OPERATOR":    2,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_support_auth_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_support_auth_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_support_auth_proto_rawDescGZIP(), []int{0}
}

// Запрос от Go-микросервиса к Django
type ValidateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JWT-токен, который фронтенд прислал при открытии сокета
	JwtToken      string `protobuf:"bytes,1,opt,name=jwt_token,json=jwtToken,proto3" json:"jwt_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_support_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_support_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_support_auth_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateRequest) GetJwtToken() string {
	if x != nil {
		return x.JwtToken
	}
	return ""
}

// Ответ от Django
type ValidateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Статус проверки: true - токен валиден, false - протух/подделан
	IsValid bool `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	// Если is_valid = true, монолит возвращает данные юзера
	User *UserProfile `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	// Если is_valid = false, монолит возвращает причину (полезно для логов Go)
	ErrorMessage  string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_support_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_support_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_support_auth_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *ValidateResponse) GetUser() *UserProfile {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *ValidateResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Вложенная структура с профилем пользователя
type UserProfile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Уникальный ID пользователя из PostgreSQL (нужен для маршрутизации в Go)
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Роль пользователя (поможет Go-сервису понять, кому слать уведомления оператора)
	Role Role `protobuf:"varint,2,opt,name=role,proto3,enum=murplace.support.v1.Role" json:"role,omitempty"`
	// Имя или Email для отображения в интерфейсе чата
	DisplayName   string `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_support_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_support_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_support_auth_proto_rawDescGZIP(), []int{2}
}

func (x *UserProfile) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserProfile) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

func (x *UserProfile) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

var File_support_auth_proto protoreflect.FileDescriptor

const file_support_auth_proto_rawDesc = "" +
	"\n" +
	"\x12support_auth.proto\x12\x13murplace.support.v1\".\n" +
	"\x0fValidateRequest\x12\x1b\n" +
	"\tjwt_token\x18\x01 \x01(\tR\bjwtToken\"\x88\x01\n" +
	"\x10ValidateResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\x124\n" +
	"\x04user\x18\x02 \x01(\v2 .murplace.support.v1.UserProfileR\x04user\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"o\n" +
	"\vUserProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12-\n" +
	"\x04role\x18\x02 \x01(\x0e2\x19.murplace.support.v1.RoleR\x04role\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName*@\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vROLE_CLIENT\x10\x01\x12\x11\n" +
	"\rROLE_OPERATOR\x10\x022v\n" +
	"\x12SupportAuthService\x12`\n" +
	"\x11ValidateWSSession\x12$.murplace.support.v1.ValidateRequest\x1a%.murplace.support.v1.ValidateResponseB,Z*pkg/api/v1/support_auth_v1;support_auth_v1b\x06proto3"

var (
	file_support_auth_proto_rawDescOnce sync.Once
	file_support_auth_proto_rawDescData []byte
)

func file_support_auth_proto_rawDescGZIP() []byte {
	file_support_auth_proto_rawDescOnce.Do(func() {
		file_support_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_support_auth_proto_rawDesc), len(file_support_auth_proto_rawDesc)))
	})
	return file_support_auth_proto_rawDescData
}

var file_support_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_support_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_support_auth_proto_goTypes = []any{
	(Role)(0),                // 0: murplace.support.v1.Role
	(*ValidateRequest)(nil),  // 1: murplace.support.v1.ValidateRequest
	(*ValidateResponse)(nil), // 2: murplace.support.v1.ValidateResponse
	(*UserProfile)(nil),      // 3: murplace.support.v1.UserProfile
}
var file_support_auth_proto_depIdxs = []int32{
	3, // 0: murplace.support.v1.ValidateResponse.user:type_name -> murplace.support.v1.UserProfile
	0, // 1: murplace.support.v1.UserProfile.role:type_name -> murplace.support.v1.Role
	1, // 2: murplace.support.v1.SupportAuthService.ValidateWSSession:input_type -> murplace.support.v1.ValidateRequest
	2, // 3: murplace.support.v1.SupportAuthService.ValidateWSSession:output_type -> murplace.support.v1.ValidateResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_support_auth_proto_init() }
func file_support_auth_proto_init() {
	if File_support_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_support_auth_proto_rawDesc), len(file_support_auth_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_support_auth_proto_goTypes,
		DependencyIndexes: file_support_auth_proto_depIdxs,
		EnumInfos:         file_support_auth_proto_enumTypes,
		MessageInfos:      file_support_auth_proto_msgTypes,
	}.Build()
	File_support_auth_proto = out.File
	file_support_auth_proto_goTypes = nil
	file_support_auth_proto_depIdxs = nil
}
