// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: support_auth.proto

package support_auth_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SupportAuthService_ValidateWSSession_FullMethodName = "/murplace.support.v1.SupportAuthService/ValidateWSSession"
)

// SupportAuthServiceClient is the client API for SupportAuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SupportAuthServiceClient interface {
	// Метод валидации сессии при подключении к WebSocket
	ValidateWSSession(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error)
}

type supportAuthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSupportAuthServiceClient(cc grpc.ClientConnInterface) SupportAuthServiceClient {
	return &supportAuthServiceClient{cc}
}

func (c *supportAuthServiceClient) ValidateWSSession(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateResponse)
	err := c.cc.Invoke(ctx, SupportAuthService_ValidateWSSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SupportAuthServiceServer is the server API for SupportAuthService service.
// All implementations must embed UnimplementedSupportAuthServiceServer
// for forward compatibility.
type SupportAuthServiceServer interface {
	// Метод валидации сессии при подключении к WebSocket
	ValidateWSSession(context.Context, *ValidateRequest) (*ValidateResponse, error)
	mustEmbedUnimplementedSupportAuthServiceServer()
}

// UnimplementedSupportAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSupportAuthServiceServer struct{}

func (UnimplementedSupportAuthServiceServer) ValidateWSSession(context.Context, *ValidateRequest) (*ValidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateWSSession not implemented")
}
func (UnimplementedSupportAuthServiceServer) mustEmbedUnimplementedSupportAuthServiceServer() {}
func (UnimplementedSupportAuthServiceServer) testEmbeddedByValue()                            {}

// UnsafeSupportAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SupportAuthServiceServer will
// result in compilation errors.
type UnsafeSupportAuthServiceServer interface {
	mustEmbedUnimplementedSupportAuthServiceServer()
}

func RegisterSupportAuthServiceServer(s grpc.ServiceRegistrar, srv SupportAuthServiceServer) {
	// If the following call panics, it indicates UnimplementedSupportAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SupportAuthService_ServiceDesc, srv)
}

func _SupportAuthService_ValidateWSSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupportAuthServiceServer).ValidateWSSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupportAuthService_ValidateWSSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupportAuthServiceServer).ValidateWSSession(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SupportAuthService_ServiceDesc is the grpc.ServiceDesc for SupportAuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SupportAuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "murplace.support.v1.SupportAuthService",
	HandlerType: (*SupportAuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateWSSession",
			Handler:    _SupportAuthService_ValidateWSSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "support_auth.proto",
}
